apiVersion: apps/v1
kind: Deployment
metadata:
  name: yessoft-next-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yessoft-next-app
  template:
    metadata:
      labels:
        app: yessoft-next-app
    spec:
      containers:
      - name: web
        image: registry.labz.org/yessoft-next:v1
        ports:
        - containerPort: 8121
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: yessoft-next-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: yessoft-next-app
  ports:
    - protocol: TCP
      port: 8121                
      targetPort: 8121          
      nodePort: 30190