apiVersion: v1
kind: Namespace
metadata:
  name: nginx-proxy-manager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-data
  namespace: nginx-proxy-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: npm-letsencrypt
  namespace: nginx-proxy-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi