apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-manager
  namespace: nginx-proxy-manager
  annotations:
    # MetalLB에게 특정 IP 할당을 요청하는 핵심 설정
    metallb.universe.tf/loadBalancerIPs: 192.168.0.231
spec:
  selector:
    app: nginx-proxy-manager
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: admin
      port: 81
      targetPort: 81
      protocol: TCP